### PR TITLE
Changed to PHP from twig for ban ip email template

### LINKED ISSUE #32: When an IP is banned, an HTTP 500 happens in the tracking request because it fails to send the email
Getting this error:

image

To reproduce, set max actions per visit for example to `3` and configure a notification email.

image

Then issue 4 tracking requests. The 4th tracking request should result in an HTTP 500.

We noticed this yesterday ourselves as pretty much all tracking requests resulted in an HTTP 500 in one account.

The problem is that we shouldn't use twig to create the email in https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/4.x-dev/BanIpNotificationEmail.php#L30

The email content is very basic anyway so we could instead simply create the email content in PHP directly.

For security we might want to call `Common::sanitizeInputValue($string)` for each of the values.

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Changed to PHP from twig for ban ip email template.
Fixes: #32

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: BanIpNotificationEmail.php [hunk 1]
```diff
@@ -53,9 +51,18 @@ public function send($ip, $email, $maxActionsAllowed, $locationData, $nowDateTim
...
+                        <br> IP as detected in header: '.\Piwik\IP::getIpFromHeader().'
+                        <br> GET request info: '.json_encode($get, JSON_HEX_APOS).'
+                        <br> POST request info: '.json_encode($post, JSON_HEX_APOS);
+        }
+
+        if(!empty($locationData)) {
+            $mailBody.='<br> '.json_encode($locationData, JSON_HEX_APOS);
+        }
+
+        $mail->setBodyHtml(Common::sanitizeInputValue($mailBody));
```
Comment (AltamashShaikh) [inline BanIpNotificationEmail.php]: @tsteur 
This works but due Common::sanitizeInputValue the email body is not rendering properly.

Comment (Findus23) [reply BanIpNotificationEmail.php]: The solution would be not to sanitize the full HTML, but every variable you plug into the HTML, right?

@Findus23 It worked, Thanks :+1:

File: BanIpNotificationEmail.php [hunk 2]
```diff
@@ -27,13 +28,10 @@ public function send($ip, $email, $maxActionsAllowed, $locationData, $nowDateTim
...
         $mail->setDefaultFromPiwik();
 
-        $view = new View('@TrackingSpamPrevention/notificationBanIpEmail.twig');
-        $view->instanceId = SettingsPiwik::getPiwikInstanceId();
-        $view->maxActionsAllowed = $maxActionsAllowed;
-        $view->ipBanned = $ip;
-        $view->ipHeader = \Piwik\IP::getIpFromHeader();
-        $view->nowDataTime = $nowDateTime;
-        $view->geoIpInfo = $locationData;
+        $mailBody = 'This is for your information. The following IP was banned because visit tried to track more than '.$maxActionsAllowed.' actions:';
```
Comment (Findus23) [inline BanIpNotificationEmail.php]: It would be really great if you could make all texts translatable.

Comment (tsteur) [reply BanIpNotificationEmail.php]: I'm not sure if we actually have translations in tracker, possible we do. If we have translations, then could make it translatable

Comment (AltamashShaikh) [reply BanIpNotificationEmail.php]: @Findus23 @tsteur 
Translation is not working, I have removed it from subject too.

Also santizing only the variable seems to work properly

File: tests/Integration/NotificationEmailTest.php [hunk 3]
```diff
@@ -37,15 +37,18 @@ public function test_send_noValidEmail()
 
     public function test_send_ValidEmail()
     {
-        $this->assertEquals('This is for your information. The following IP was banned because visit tried to track more than 112 actions:
-
-"10.10.10.10"
-
-Current date (UTC): 2020-12-14 01:42:27
```
Comment (AltamashShaikh) [inline tests/Integration/NotificationEmailTest.php:44]: @tsteur 
This is not being returned currently due to
`SettingsPiwik::getPiwikInstanceId()` is returning `false`

Did I miss anything here ?

File: BanIpNotificationEmail.php (hunk 2 above)
Comment (Findus23) [reply BanIpNotificationEmail.php]: Ah, that's a pity as unlike other tracker errors it's a user-facing text, but it makes sense that we can't easily translate it.

File: BanIpNotificationEmail.php [hunk 4]
```diff
@@ -53,18 +50,27 @@ public function send($ip, $email, $maxActionsAllowed, $locationData, $nowDateTim
             $post = [];
         }
 
-        $view->getRequest = $get;
-        $view->postRequest = $post;
-        $mail->setBodyText($view->render());
+        if (!empty($instanceId)) {
+            $mailBody .= '<br> Current date (UTC): ' . Common::sanitizeInputValue($nowDateTime) . '
+                        <br> IP as detected in header: ' . Common::sanitizeInputValue(\Piwik\IP::getIpFromHeader()) . '
```
Comment (tsteur) [inline BanIpNotificationEmail.php]: @AltamashShaikh all this should still be there when an instanceId is set. It's only the first line that we don't need to show when instanceId is not set. This line seems to have actually gone? I'm meaning `{% if instanceId is not empty %}Instance ID: {{ instanceId }}{% endif %}`

image

Comment (tsteur) [reply BanIpNotificationEmail.php]: Also the IP we already have as a variable above and shouldn't use `\Piwik\IP::getIpFromHeader()`

**Review by tsteur — CHANGES_REQUESTED** [review]
@AltamashShaikh mentioned a few issues as a comment. Also the email is now HTML vs before it was text. Can we change this back again?

File: BanIpNotificationEmail.php (hunk 4 above)
Comment (AltamashShaikh) [reply BanIpNotificationEmail.php]: @tsteur 
Fixed and reverted back to setBodyText

File: BanIpNotificationEmail.php [hunk 5]
```diff
@@ -53,17 +50,29 @@ public function send($ip, $email, $maxActionsAllowed, $locationData, $nowDateTim
...
         }
 
-        $view->getRequest = $get;
-        $view->postRequest = $post;
-        $mail->setBodyText($view->render());
+        if (!empty($instanceId)) {
+            $mailBody .= PHP_EOL.'Instance ID: ' . Common::sanitizeInputValue($instanceId);
+        }
+        $mailBody .= PHP_EOL.'Current date (UTC): ' . Common::sanitizeInputValue($nowDateTime) . '
+IP as detected in header: ' . Common::sanitizeInputValue($ip) . '
```
Comment (tsteur) [inline BanIpNotificationEmail.php]: @AltamashShaikh sorry just seeing we used to use `\Piwik\IP::getIpFromHeader();` there before. Bit confusing we're reporting two different IPs. Let's maybe change it back to `\Piwik\IP::getIpFromHeader();` for now. Then we should be good to merge.

File: BanIpNotificationEmail.php [hunk 6]
```diff
@@ -53,17 +50,29 @@ public function send($ip, $email, $maxActionsAllowed, $locationData, $nowDateTim
...
+GET request info: ' . json_encode($get, JSON_HEX_APOS) . '
```
Comment (tsteur) [inline BanIpNotificationEmail.php]: Out of curiousity: Any particular reason we are using `JSON_HEX_APOS` option here?

**Review by tsteur — CHANGES_REQUESTED** [review]
One last change @AltamashShaikh  and we should be also removing the no longer needed twig file.

File: BanIpNotificationEmail.php (hunk 6 above)
Comment (AltamashShaikh) [reply BanIpNotificationEmail.php]: Just to resolve any encoding issues since it has $_GET and $_POST.
In past I have seen `json_encode` failing due to such issues.

File: BanIpNotificationEmail.php (hunk 5 above)
Comment (AltamashShaikh) [reply BanIpNotificationEmail.php]: Reverted back

File: BanIpNotificationEmail.php (hunk 6 above)
Comment (AltamashShaikh) [reply BanIpNotificationEmail.php]: I have removed `JSON_HEX_APOS`

**Review by tsteur — APPROVED** [review]
feel free to merge if tests pass 👍 

since we're having a problem with this on cloud production might be good to trigger a release after merging already.
